version: '2.1'
services:

    service:
        build: ./
        privileged: true
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./src:/app/src
            - /dev/bus/usb/001:/dev/bus/usb/001
            - ./data:/data

        environment:
            - PORT=80
            - LOG_LEVEL=verbose
            - NODE_ENV=developer
            - GATHER_SAMPLES=false
            # - PREDICTOR_SERVICE=http://172.16.135.171:9876/predict
            - PREDICTOR_SERVICE=http://172.16.135.230:9779/predict

